### ISSUE TITLE
upip install on loboris

### ISSUE THREAD

**Issue by SebastianRoll** [bytebarista/iot_workshop#3]
EMOMEM

**Comment by sindresf** [comment]
Also: "[Errno 19] ENODEV, packages may be partially installed"

**Comment by jonassa** [comment]
Relatert?: [https://forum.micropython.org/viewtopic.php?t=1855](https://forum.micropython.org/viewtopic.php?t=1855)

**Comment by mallport** [comment]
Solved by using the second parameter to specify the install directory when calling upip.install() in REPL, like so:

import upip
upip.install("micropython-uasyncio","/flash")

Solves the ENODEV issue
